In [1]:
import numpy as np
from dense_layer import DenseLayer

In [2]:
layer0 = DenseLayer(3, 2)
layer1 = DenseLayer(2, 1)
inp = np.random.random((1, 3))
inp

array([[0.93154021, 0.42062102, 0.11368714]])

In [3]:
def forward(inp: np.ndarray) -> np.ndarray:
  global layer0
  global layer1
  return layer1.forward(layer0.forward(inp))


In [4]:
forward(inp)

array([[2.15250017]])

In [5]:
def backward(num_epochs: int):
  global layer0
  global layer1
  for epoch in range(num_epochs):
    layer0.backprop(layer1.backprop())

In [10]:
backward(1000000)
forward(inp)

array([[-7490.60027655]])