In [1]:
import numpy as np

In [2]:
NUM_FEATURES = None
NUM_SAMPLES = None
NUM_NEURONS_1 = None
NUM_NEURONS_2 = None

In [3]:
num_features = NUM_FEATURES or 3
num_samples = NUM_SAMPLES or 4
inputs = np.random.rand(num_samples, num_features)
inputs

array([[0.17389157, 0.8822107 , 0.62710725],
       [0.87809959, 0.68970155, 0.05376261],
       [0.39182733, 0.78630644, 0.8565094 ],
       [0.17302197, 0.91707716, 0.09923569]])

In [4]:
num_neurons = NUM_NEURONS_1 or 5
weights = np.random.rand(num_neurons, num_features)
weights

array([[0.50697276, 0.82929899, 0.94104568],
       [0.92268387, 0.61979064, 0.74562404],
       [0.80237475, 0.2290207 , 0.34754076],
       [0.01158265, 0.50561906, 0.64696144],
       [0.67579579, 0.40460699, 0.92571552]])

In [5]:
biases = np.random.rand(1, num_neurons)
biases

array([[0.82726694, 0.87700488, 0.52434645, 0.82900795, 0.22868672]])

In [6]:
output = inputs @ weights.T + biases
output

array([[2.23717823, 2.05182399, 1.08386249, 1.68279883, 1.28367344],
       [1.89500138, 2.15477047, 1.40555202, 1.22268725, 1.15092968],
       [2.48401033, 2.364517  , 1.31649118, 1.78524643, 1.6045111 ],
       [1.76890084, 1.67903781, 0.907693  , 1.35890536, 0.80853408]])

In [7]:
inputs2 = output # output from previous layer becomes input for new layer

In [8]:
num_neurons_2 = NUM_NEURONS_2 or 6 # number of neurons in second layer (hidden layer)
weights2 = np.random.rand(num_neurons_2, num_neurons)
weights2

array([[2.54182215e-01, 2.31147226e-01, 2.61481790e-01, 6.56322171e-01,
        5.13032154e-01],
       [1.33009566e-01, 4.60301356e-01, 7.23747090e-01, 5.30373458e-01,
        2.37740215e-01],
       [4.88527053e-01, 9.12211888e-01, 1.55440053e-01, 5.76477552e-02,
        3.07427888e-01],
       [4.96346790e-01, 9.39299497e-01, 2.02576533e-01, 8.53753871e-01,
        1.75244472e-01],
       [8.34877456e-01, 8.34891673e-01, 4.65256276e-01, 3.95523501e-01,
        4.46017179e-01],
       [4.88560986e-01, 3.85994700e-01, 3.53100105e-01, 4.43723099e-02,
        6.55700543e-04]])

In [9]:
biases2 = np.random.rand(1, num_neurons_2)
biases2

array([[0.08432705, 0.97740084, 0.69908215, 0.78716966, 0.95937269,
        0.06043838]])

In [11]:
output2 = inputs2 @ weights2.T + biases2
output2

array([[3.17368562, 4.20155927, 4.32382471, 5.70608093, 6.28259384,
        2.40365291],
       [2.82453886, 4.16066524, 4.23324097, 5.28202223, 5.9913444 ,
        2.3693008 ],
       [3.60137091, 4.67729915, 4.87035128, 6.31312281, 7.04158468,
        2.73184071],
       [2.466084  , 3.55543353, 3.56287193, 4.72801642, 5.15841177,
        1.95408844]])