In [8]:
from dense_layer import DenseLayer
from activation import ReLU

import numpy as np

In [9]:
NUM_FEATURES = 3
NUM_SAMPLES = 1
inputs = np.random.rand(NUM_SAMPLES, NUM_FEATURES) * 2 - 1 # [-1, 1)
inputs

array([[-0.9166803 ,  0.43681802, -0.89509366]])

In [10]:
layer0 = DenseLayer(NUM_FEATURES, 2)
print("Weights:")
print(layer0.weights)
print("\nBiases:")
print(layer0.biases)

Weights:
[[0.36044087 0.89169629 0.34334447]
 [0.04332095 0.17826426 0.48170211]]

Biases:
[[0.4124405 0.0650511]]


In [11]:
outputs = layer0.forward(inputs)
outputs

array([[ 0.16421501, -0.32795982]])

In [12]:
f = ReLU()
f(outputs)

array([[0.16421501, 0.        ]])

In [13]:
arr = np.array([[0, 1, 2], [2, 1, 0]])
print(arr)
exp = np.exp(arr - np.max(arr))
print(exp)
exp / np.sum(exp, axis=1, keepdims=True)

[[0 1 2]
 [2 1 0]]
[[0.13533528 0.36787944 1.        ]
 [1.         0.36787944 0.13533528]]


array([[0.09003057, 0.24472847, 0.66524096],
       [0.66524096, 0.24472847, 0.09003057]])

In [14]:
np.argmax(np.array([0, 0, 1, 0, 0]))

np.int64(2)

In [15]:
inp = np.array([[.7, .1, .2],[.5, .2, .3],[.2, .6, .2]])
truth = np.array([0, 2, 1])
print(inp[ range( len(truth) ), truth ])

[0.7 0.3 0.6]


In [16]:
inp = np.array([[.7, .1, .2],[.5, .2, .3],[.2, .6, .2]])
truth = np.array([[1, 0, 0],[0, 0, 1],[0, 1, 0]])
print(inp[range(len(truth)), np.argmax(truth, axis=1)])

[0.7 0.3 0.6]


In [17]:
from loss import CrossEntropy, accuracy
f = CrossEntropy()

In [18]:
loss = f(
  np.array([[1, 0, 0],[0, 0, 1],[0, 1, 0]]), 
  np.array([[.7, .1, .2],[.5, .2, 0],[.2, .6, .2]])
)
print(loss)
print(np.mean(loss))
accuracy(
  np.array([[1, 0, 0],[0, 0, 1],[0, 1, 0]]),
  np.array([[.7, .1, .2],[.5, .2, 0],[.2, .6, .2]])
)

[ 0.35667494 16.11809565  0.51082562]
5.661865406221015


np.float64(0.6666666666666666)