In [2]:
from dense_layer import DenseLayer
from activation import ReLU

import numpy as np

In [12]:
NUM_FEATURES = 3
NUM_SAMPLES = 1
inputs = np.random.rand(NUM_SAMPLES, NUM_FEATURES) * 2 - 1
inputs

array([[ 0.17622158, -0.90343292, -0.59568258]])

In [13]:
layer0 = DenseLayer(2, NUM_FEATURES)
print("Weights:")
print(layer0.weights)
print("\nBiases:")
print(layer0.biases)

Weights:
[[0.55010959 0.38643355 0.04235733]
 [0.2102391  0.39690613 0.73703126]]

Biases:
[[0.43642155 0.32629571]]


In [14]:
outputs = layer0.forward(inputs)
outputs

array([[ 0.15901441, -0.43427037]])

In [15]:
f = ReLU()
f(outputs)

array([[0.15901441, 0.        ]])

In [20]:
arr = np.array([[0, 1, 2], [2, 1, 0]])
print(arr)
exp = np.exp(arr - np.max(arr))
print(exp)
exp / np.sum(exp, axis=1, keepdims=True)

[[0 1 2]
 [2 1 0]]
[[0.13533528 0.36787944 1.        ]
 [1.         0.36787944 0.13533528]]


array([[0.09003057, 0.24472847, 0.66524096],
       [0.66524096, 0.24472847, 0.09003057]])