In [1]:
from dense_layer import DenseLayer
from activation import ReLU

import numpy as np

In [2]:
NUM_FEATURES = 3
NUM_SAMPLES = 1
inputs = np.random.rand(NUM_SAMPLES, NUM_FEATURES) * 2 - 1
inputs

array([[-0.23883764,  0.49586391,  0.74874545]])

In [3]:
layer0 = DenseLayer(2, NUM_FEATURES)
print("Weights:")
print(layer0.weights)
print("\nBiases:")
print(layer0.biases)

Weights:
[[0.30822319 0.4316984  0.07726399]
 [0.40911319 0.98075345 0.58638497]]

Biases:
[[0.72719591 0.42093481]]


In [4]:
outputs = layer0.forward(inputs)
outputs

array([[0.92549532, 1.2485965 ]])

In [5]:
f = ReLU()
f(outputs)

array([[0.92549532, 1.2485965 ]])

In [6]:
arr = np.array([[0, 1, 2], [2, 1, 0]])
print(arr)
exp = np.exp(arr - np.max(arr))
print(exp)
exp / np.sum(exp, axis=1, keepdims=True)

[[0 1 2]
 [2 1 0]]
[[0.13533528 0.36787944 1.        ]
 [1.         0.36787944 0.13533528]]


array([[0.09003057, 0.24472847, 0.66524096],
       [0.66524096, 0.24472847, 0.09003057]])

In [7]:
np.argmax(np.array([0, 0, 1, 0, 0]))

np.int64(2)

In [8]:
inp = np.array([[.7, .1, .2],[.5, .2, .3],[.2, .6, .2]])
truth = np.array([0, 2, 1])
print(inp[range(len(truth)), truth])

[0.7 0.3 0.6]


In [9]:
inp = np.array([[.7, .1, .2],[.5, .2, .3],[.2, .6, .2]])
truth = np.array([[1, 0, 0],[0, 0, 1],[0, 1, 0]])
print(inp[range(len(truth)), np.argmax(truth, axis=1)])

[0.7 0.3 0.6]


In [10]:
from loss import CrossEntropy
f = CrossEntropy()

In [11]:
loss = f(
  np.array([[1, 0, 0],[0, 0, 1],[0, 1, 0]]), 
  np.array([[.7, .1, .2],[.5, .2, 0],[.2, .6, .2]])
)
print(loss)
np.average(loss)

[ 0.35667494 16.11809565  0.51082562]


np.float64(5.661865406221015)